/**
 * The commit rule must exist where other tools will find it.
 *
 * It lived in one contributor's editor configuration. On 2026-10-06 a session
 * using a different tool committed here, having never seen it, and its commit
 * message broke the build for every branch — because the attribution scan reads
 * `git log --all` on purpose, so one bad message anywhere reddens everything.
 *
 * A pointer saying "see AGENTS.md" is one indirection away from being ignored by
 * something that only greps its own file, so the rule is COPIED. Copies drift,
 * which is the fault this project has written down more than once, so the copies
 * are generated by `scripts/sync-agent-rules.sh` and these checks fail when one
 * of them falls behind.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const root = fileURLToPath(new URL('..', import.meta.url));
const read = (p) => readFileSync(join(root, p), 'utf8');

/**
 * The same text with its line wrapping and markdown emphasis removed.
 *
 * Matching a one-line pattern against wrapped prose fails on where the
 * paragraph happens to break: `/fresh clone has no hooks/` did not match
 * "so **a fresh\nclone has no hooks**", and the check accused a correct
 * document. That is the thirteenth check here in a week that compared the wrong
 * two things, and the first with a general fix rather than a reworded regex —
 * so every prose assertion below reads this, not the raw file.
 */
const flat = (p) => read(p).replace(/`/g, '').replace(/\s+/g, ' ');

const SOURCE = 'AGENTS.md';
/** Each copy, and the header it is allowed to carry above the shared body. */
const COPIES = ['.cursorrules', '.cursor/rules/repository-rules.mdc'];
/** CONTRIBUTING.md is NOT a copy: it has its own content and carries a pointer
 *  section. A first version of the sync script `cp`-ed over it and destroyed the
 *  hook-installation instructions — caught by an existing test that asserted
 *  them. Files with their own content are not generated from anything. */
const POINTS_HERE = 'CONTRIBUTING.md';

test('the rule exists at the repository root, where a tool will meet it', () => {
  for (const f of [SOURCE, ...COPIES, POINTS_HERE]) {
    assert.ok(existsSync(join(root, f)), `${f} is missing`);
  }
});

test('CONTRIBUTING.md keeps its own content and points here', () => {
  const c = read(POINTS_HERE);
  // The content a first version of the sync script destroyed.
  assert.match(c, /setup-hooks\.sh/, 'the hook installation route is gone');
  assert.match(c, /This repository is public/, 'the public-repository rules are gone');
  assert.match(c, /AGENTS\.md/, 'it does not point at the full rules');
  assert.ok(!c.startsWith('# Rules for anything that commits'),
    'CONTRIBUTING.md has been overwritten with AGENTS.md again');
});

test('every copy carries the whole rule, unchanged', () => {
  const source = read(SOURCE).trim();
  const drifted = [];
  for (const f of COPIES) {
    const body = read(f);
    if (!body.includes(source)) {
      drifted.push(`${f} does not contain AGENTS.md verbatim — run scripts/sync-agent-rules.sh`);
    }
  }
  assert.deepEqual(drifted, []);
});

test('the rule states the trailer ban, the reason, and how to install the hooks', () => {
  const s = flat(SOURCE);
  assert.match(s, /Co-Authored-By/i, 'the banned trailer is not named');
  // Read from the file rather than written from memory: the first version of
  // this expected "refs/pull/* permanently" and the text had a backtick between
  // the two, so it accused a correct document. Twelfth time this week.
  assert.match(s, /GitHub keeps refs\/pull\/\* permanently/,
    'the reason — GitHub keeps the ref for ever — is not stated');
  assert.match(s, /core\.hooksPath/, 'it does not say how to install the hooks');
  assert.match(s, /fresh\W{0,4}clone has no hooks/,
    'it does not warn that a fresh clone is unguarded until something sets hooksPath');
  // The thing the rule is FOR: every commit authored by one person. Asserted
  // WITHOUT the address, because this file is tracked in a public repository
  // too — and the first version of this line carried the address escaped for
  // the regex, which is exactly why step 3 of the sweep never saw it.
  assert.match(s, /authored by the repository owner and nothing\W{0,4}else/);
  assert.match(s, /git config user\.name/,
    'it does not say where the authorship actually comes from');
  assert.doesNotMatch(SOURCE, /@(gmail|outlook|yahoo|hotmail|proton)\\?\./i,
    'the rule must be statable without a personal address: this file is public');
});

test('the hooks exist and the commit-msg hook calls the one script', () => {
  for (const h of ['commit-msg', 'pre-commit', 'pre-push']) {
    assert.ok(existsSync(join(root, '.githooks', h)), `.githooks/${h} is missing`);
  }
  const hook = read('.githooks/commit-msg');
  assert.match(hook, /check-commit-messages\.sh.*--message/,
    'the commit-msg hook must call the same script CI runs, in its one-message mode');
  // One pattern list. Two would drift, which is how a clean hook and a red CI
  // become possible for a second time.
  const script = read('scripts/check-commit-messages.sh');
  assert.equal((script.match(/^PATTERNS=/gm) ?? []).length, 1,
    'the pattern list must be defined exactly once');
  assert.match(script, /--message/, 'the script has no one-message mode');
});

test('npm install installs the hooks, because a fresh clone has none', () => {
  // core.hooksPath lives in .git/config, which is not committed. Without this
  // a fresh clone — which is what another tool's session gets — is unguarded.
  const pkg = JSON.parse(read('package.json'));
  assert.match(pkg.scripts.prepare ?? '', /core\.hooksPath \.githooks/,
    'package.json has no `prepare` script setting core.hooksPath');
});
