/**
 * What a learner can actually practise, and whether the map tells the truth.
 *
 * The learn map is the portal's main navigation. It offered 42 cells, showed a
 * dash in 24, and **every one of the 18 clickable cells led to a page saying
 * "Not built yet"**. A learner who hits three dead ends stops believing the
 * map.
 *
 * Listing each level's concepts fixes the dead end only if the list also says
 * which concepts have nothing behind them, because most do not:
 *
 *     261 live non-group concepts
 *      65 with any exercise at all
 *     196 with none
 *       0 of 71 at C1 and C2
 *
 * `content/concept-material.json` is generated by
 * `scripts/build-concept-material.py`. These checks recompute it from the
 * content it is derived from and compare — the only shape of check that can see
 * a generator going wrong, which is how the non-deterministic build was caught.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { cellState, conceptsFor } from '../web/src/lib/material.ts';

const root = fileURLToPath(new URL('..', import.meta.url));
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));
const LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];

const concepts = read('content/concepts.json').concepts;
const live = concepts.filter((c) => !c.isGroup && !c.retired);
const generated = read('content/concept-material.json');
const material = new Map(Object.entries(generated.material));

/** The same count, from the content, independently of the generator. */
function recount() {
  const liveIds = new Set(live.map((c) => c.id));
  const out = new Map();
  const bump = (id, key, n = 1) => {
    if (!liveIds.has(id)) return;
    const m = out.get(id) ?? { cards: 0, verbForms: 0, examItems: 0, total: 0 };
    m[key] += n; m.total += n; out.set(id, m);
  };
  for (const d of read('content/decks.json').decks) {
    for (const card of read(`content/${d.file}`).cards) {
      for (const id of card.conceptIds ?? []) bump(id, 'cards');
    }
  }
  for (const lvl of LEVELS) {
    for (const v of read(`content/verbs/${lvl}.json`).verbs) {
      if (v.produce === false) continue;
      for (const t of v.tenses) {
        if (t.conceptId && t.produced) {
          bump(t.conceptId, 'verbForms', t.forms.filter(Boolean).length);
        }
      }
    }
  }
  for (const paper of read('content/exam-papers.json').papers) {
    for (const item of paper.items) for (const id of item.conceptIds ?? []) bump(id, 'examItems');
  }
  return out;
}

test('the generated counts match the content they are derived from', () => {
  const mine = recount();
  const bad = [];
  for (const [id, m] of mine) {
    const theirs = material.get(id);
    if (!theirs) { bad.push(`${id}: counted ${m.total}, generated nothing`); continue; }
    for (const k of ['cards', 'verbForms', 'examItems', 'total']) {
      if (theirs[k] !== m[k]) bad.push(`${id}.${k}: generated ${theirs[k]}, content says ${m[k]}`);
    }
  }
  for (const id of material.keys()) {
    if (!mine.has(id)) bad.push(`${id}: generated, and nothing in the content reaches it`);
  }
  assert.deepEqual(bad.slice(0, 8), [],
    'regenerate with scripts/build-concept-material.py');
  assert.equal(generated.liveConcepts, live.length);
  assert.equal(generated.conceptsWithMaterial, material.size);
  console.log(`    ${material.size} of ${live.length} live concepts have an exercise`);
});

test('the gap is recorded, not implied', () => {
  // 196 of 261 is the number a reader needs, and it belongs in the file rather
  // than being left to be worked out from what is absent.
  assert.match(generated.note, /has NO exercise/);
  assert.ok(generated.liveConcepts - generated.conceptsWithMaterial > 150,
    'the gap has closed enough that this note is misleading — rewrite it');
});

test('no cell of the learn map is clickable and empty of everything', () => {
  // THE DEFECT THIS REPLACES. A cell is clickable when the taxonomy has
  // concepts there; the page it leads to now lists them with their state and
  // says which have nothing. What must never happen again is a clickable cell
  // whose page can say nothing at all.
  const TAUGHT = ['grammar', 'vocabulary', 'phonetics'];
  const lying = [];
  for (const lvl of LEVELS) {
    for (const skill of TAUGHT) {
      const cell = cellState(concepts, material, lvl, skill);
      if (cell.state !== 'locked' && cell.concepts === 0) {
        lying.push(`${lvl}/${skill}: clickable with no concepts`);
      }
      if (cell.state === 'locked' && cell.concepts > 0) {
        lying.push(`${lvl}/${skill}: locked while holding ${cell.concepts} concepts`);
      }
    }
  }
  assert.deepEqual(lying, []);
});

test('the cell state says which of the four things a cell is', () => {
  const seen = new Map();
  for (const lvl of LEVELS) {
    for (const skill of ['grammar', 'vocabulary', 'phonetics', 'listening']) {
      const c = cellState(concepts, material, lvl, skill);
      seen.set(`${lvl}/${skill}`, c);
    }
  }
  // Listening is in no level of the taxonomy, so every one of its cells is locked.
  for (const lvl of LEVELS) assert.equal(seen.get(`${lvl}/listening`).state, 'locked');
  // C1 and C2 have concepts and not one exercise: `listed`, which is the state
  // that did not exist before and is why those cells used to lie.
  assert.equal(seen.get('C1/grammar').state, 'listed');
  assert.equal(seen.get('C2/grammar').state, 'listed');
  assert.equal(seen.get('C1/grammar').withMaterial, 0);
  // A1 to B2 have some and not others.
  for (const lvl of ['A1', 'A2', 'B1', 'B2']) {
    assert.equal(seen.get(`${lvl}/grammar`).state, 'partial', `${lvl}/grammar`);
  }
  const summary = LEVELS.map((l) => `${l} ${seen.get(`${l}/grammar`).withMaterial}/${seen.get(`${l}/grammar`).concepts}`);
  console.log(`    grammar by level: ${summary.join(' · ')}`);
});

test('usage concepts are unreachable from the map, and that is recorded', () => {
  // 35 live concepts are typed `usage` and the map has no usage column, so no
  // cell leads to them. Found while rewriting the map; not fixed here because
  // adding a column is a design decision, and recorded so it is not lost.
  const usage = live.filter((c) => c.type === 'usage');
  assert.ok(usage.length > 20, `${usage.length} usage concepts`);
  const withMaterial = usage.filter((c) => material.has(c.id));
  console.log(`    ${usage.length} usage concepts, ${withMaterial.length} with exercises, `
    + 'and no column on the map leads to any of them');
});
