/**
 * Generates the service worker after the build, with the real hashed asset
 * names baked in. Writing the list by hand would mean a stale name shipping
 * silently, which is the same failure as a check that cannot fail.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(root, 'dist');

const walk = (dir, prefix = '') => readdirSync(resolve(dist, dir), { withFileTypes: true })
  .flatMap((e) => e.isDirectory() ? walk(`${dir}/${e.name}`, `${prefix}${e.name}/`)
                                  : [`${prefix}${e.name}`]);

const assets = walk('assets', 'assets/');
const fonts = walk('fonts', 'fonts/').filter((f) => f.endsWith('.woff2') || f.endsWith('.css'));
const content = walk('content', 'content/');
const shell = ['./', 'index.html', ...assets, ...fonts, ...content];
const version = readFileSync(resolve(dist, 'index.html'), 'utf8').length + '-' + assets.join('').length;

writeFileSync(resolve(dist, 'sw.js'), `/* generated by scripts/sw.mjs — do not edit */
const CACHE = 'flw-${version}';
const SHELL = ${JSON.stringify(shell, null, 2)};

self.addEventListener('install', (e) => {
  // addAll fails the whole install if one file is missing, which is the point:
  // a half-cached shell fails later and less comprehensibly than not at all.
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((names) => Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', (e) => {
  const { request } = e;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;
  e.respondWith(caches.open(CACHE).then(async (cache) => {
    const hit = await cache.match(request, { ignoreSearch: true });
    const net = fetch(request).then((r) => { if (r.ok) cache.put(request, r.clone()); return r; }).catch(() => null);
    if (hit) return hit;                       // instant, and works offline
    const fresh = await net;
    if (fresh) return fresh;
    // A navigation offline still gets the shell; the app renders from cache.
    return (await cache.match('index.html')) ?? new Response('Offline', { status: 503 });
  }));
});
`);
console.log(`service worker: ${shell.length} files precached (${assets.length} assets, ${fonts.length} fonts, ${content.length} content)`);
