#!/usr/bin/env bash
# Copy AGENTS.md into the other files the common tools read.
#
# Four copies of one rule is a drift hazard, and this project's own lesson is
# that one file needs one source. But a tool reads the file it reads: Cursor
# looks at .cursorrules and .cursor/rules/*.mdc, GitHub shows CONTRIBUTING.md,
# and several agents look for AGENTS.md. A pointer saying "see AGENTS.md" is one
# indirection away from being ignored by something that only greps its own file.
#
# So: AGENTS.md is the source, the rest are generated, and
# tests/agent-rules-are-everywhere.test.js fails if any of them drifts.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# CONTRIBUTING.md is NOT generated. It had its own content — the public-repository
# rules and the hook installation route — and a first version of this script
# overwrote it with `cp`, which an existing test caught by asserting the install
# instruction it had destroyed. It carries a short section pointing here instead,
# maintained by hand.

{
  echo "# Cursor reads this file. The rules are in AGENTS.md at the repository root."
  echo "# They are repeated here so that no tool has to be told where to look."
  echo "# Generated by scripts/sync-agent-rules.sh — edit AGENTS.md, not this."
  echo
  cat AGENTS.md
} > .cursorrules

mkdir -p .cursor/rules
{
  echo "---"
  echo "description: Rules for anything that commits to this repository"
  echo "alwaysApply: true"
  echo "---"
  echo
  echo "<!-- Generated by scripts/sync-agent-rules.sh — edit AGENTS.md, not this. -->"
  echo
  cat AGENTS.md
} > .cursor/rules/repository-rules.mdc

echo "synced AGENTS.md -> .cursorrules, .cursor/rules/repository-rules.mdc"
echo "(CONTRIBUTING.md is hand-maintained and carries a pointer section)"
